# Generated by Django 4.0.6 on 2023-03-01 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials', '0004_alter_person_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='person',
            name='subject',
            field=models.ManyToManyField(related_name='subjects', to='Tutorials.subject'),
        ),
    ]
