# Generated by Django 4.0.1 on 2023-03-19 07:48

import Tutorials.validators
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials', '0008_customeuser_alter_person_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('persons', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, validators=[Tutorials.validators.username_validate_error]),
        ),
        migrations.AlterField(
            model_name='person',
            name='subject',
            field=models.ManyToManyField(related_name='subjects', to='Tutorials.Subject'),
        ),
    ]
